#!/usr/bin/env bash
# Installs Nginx with the following config
# Listening on port 80
# Returns a page that contains 'Hello World!'

sudo apt-get -y update;
sudo apt-get -y install nginx;
sudo ufw allow 'Nginx HTTP';
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html';
sudo service nginx start;
