#!/usr/bin/env bash
# Installs Nginx with the following config
# Listening on port 80
# Returns a page that contains 'Hello World!'

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
